final List<Map<String, dynamic>> events = [
  {
    "id": 1,
    "title": "Comentario del Archivo: \"frontend Module For Save_edit Funct",
    "type": "standup",
    "code": "standup_00001",
    "location": "Atenas Estadio",
    "date": "2025-07-11T20:00",
    "price": "Libre y Gratuita",
    "imageUrl":
        "https://misty-bread-5506.tester-passalia.workers.dev/cine_0004.jpg",
    "description":
        "El director del espacio declarado patrimonio de la humanidad por la Unesco y tres empresarios están acusados tras la investigación federal. La construcción de una cancha de fútbol también figura en la causa.",
    "address": "Alejandro Aguado 687",
    "district": "Gral Paz",
    "websiteUrl": "https://www.estadioatenas.com",
    "lat": -31.39636078064314,
    "lng": -64.17225774519973,
  },
  {
    "id": 2,
    "title": "Estados Unidos",
    "type": "standup",
    "code": "standup_00002",
    "location": "Atenas Estadio",
    "date": "2025-07-26T16:00",
    "price": "\$ 58.000",
    "imageUrl":
        "https://misty-bread-5506.tester-passalia.workers.dev/teatro_0001.jpg",
    "description":
        "La Estancia Jesuítica de Jesús María, un predio de gran valor patrimonial y cultural, fue escenario de una fiesta electrónica que atraajo a cerca de dos mil personas, lo que desencadenó una investigación en el fuero federal. Entre los imputados se encuentran Carlos Ferreyra, director del espacio, y tres empresarios de la zona.\n\n\"Lo que estamos investigando es la organización de un evento en un lugar protegido por una competencia especial de la Secretaría de Cultura de la Nación, que había sido solicitada y negada la autorización para realizar este tipo de eventos\", expresó el fiscal Maximiliano Hairabedian.",
    "address": "Alejandro Aguado 687",
    "district": "Gral Paz",
    "websiteUrl": "https://www.estadioatenas.com",
    "lat": -31.39636078064314,
    "lng": -64.17225774519973,
  },
  {
    "id": 3,
    "title": "Proyecto Carayá: Un Tesoro para Visitar en Vacaciones",
    "type": "ninos",
    "code": "ninos_00003",
    "location": "Casa Grote",
    "date": "2025-07-23T14:00",
    "price": "A la Gorra",
    "imageUrl":
        "https://misty-bread-5506.tester-passalia.workers.dev/ninos_00003.jpg",
    "description": "Proyecto Carayá: un tesoro para visitar en vacaciones",
    "address": "Padre F. Grote 1080",
    "district": "Alta Córdoba",
    "websiteUrl": "https://www.estadioatenas.com",
    "lat": -31.39319638828705,
    "lng": -64.16783225689021,
  },
  {
    "id": 4,
    "title": "fiesta latina",
    "type": "teatro",
    "code": "teatro_00004",
    "location": "Atenas Estadio",
    "date": "2025-07-19T23:45",
    "price": "\$ 14.000",
    "imageUrl":
        "https://misty-bread-5506.tester-passalia.workers.dev/teatro_0002.jpg",
    "description":
        "Pese a contar con habilitaciones municipales, personal policial asignado y servicios de emergencias disponibles, la denuncia apunta la intervención del sitio declarado patrimonio de la humanidad por la Unesco en el 2000 sin autorización a nivel nacional.",
    "address": "Alejandro Aguado 687",
    "district": "Gral Paz",
    "websiteUrl": "https://990arteclub.com",
    "lat": -31.39636078064314,
    "lng": -64.17225774519973,
  },
  {
    "id": 5,
    "title": "Feria piojo",
    "type": "ferias",
    "code": "ferias_00005",
    "location": "Centro Cultural La Piojera",
    "date": "2025-07-19T20:00",
    "price": "Libre y Gratuita",
    "imageUrl":
        "https://misty-bread-5506.tester-passalia.workers.dev/teatro_0007.jpg",
    "description":
        "Acá el problema no es la realización de una fiesta sino hacerla en un lugar que es patrimonio de la humanidad, que requiere cuidados especiales y permiso especiales para cualquier intervención que pueda afectarlo\", dijo el fiscal federal a cargo de la investigación.",
    "address": "Av. Colón 1559",
    "district": "Alberdi",
    "websiteUrl": "https://cultura.cordoba.gob.ar/centro-cultural-la-piojera",
    "lat": -31.40740975245425,
    "lng": -64.20402027408333,
  },
  {
    "id": 6,
    "title": "fiesta latina",
    "type": "arte",
    "code": "arte_00006",
    "location": "Atenas Estadio",
    "date": "2025-08-16T23:45",
    "price": "\$ 14.000",
    "imageUrl":
        "https://misty-bread-5506.tester-passalia.workers.dev/teatro_0002.jpg",
    "description":
        "Pese a contar con habilitaciones municipales, personal policial asignado y servicios de emergencias disponibles, la denuncia apunta la intervención del sitio declarado patrimonio de la humanidad por la Unesco en el 2000 sin autorización a nivel nacional.",
    "address": "Alejandro Aguado 687",
    "district": "Gral Paz",
    "websiteUrl": "https://990arteclub.com",
    "lat": -31.39636078064314,
    "lng": -64.17225774519973,
  },
];
